### ISSUE TITLE
Possible AV in MPShellUtilities initialization in PIDLIsFolder

### ISSUE THREAD

**Issue by yonojoy** [pyscripter/MustangpeakCommonLib#11]
The current code reads:

      PIDLMgr.StripLastID(APIDL, Last_CB, LastPIDL);
      try
        if Succeeded( Desktop.BindToObject(APIDL, nil, IShellFolder, Pointer( Parent))) then
        begin
          LastPIDL^.mkid.cb := Last_CB;
          if Succeeded( Parent.GetAttributesOf(1, LastPIDL, Flags)) then
            Result := Flags and SFGAO_FOLDER <> 0
        end
      finally
        if LastPIDL^.mkid.cb = 0 then
          LastPIDL^.mkid.cb := Last_CB;
      end

It should be replaced by:

      PIDLMgr.StripLastID(APIDL, Last_CB, LastPIDL);
      if Assigned(LastPIDL) then
      try
        if Succeeded( Desktop.BindToObject(APIDL, nil, IShellFolder, Pointer( Parent))) then
        begin
          LastPIDL^.mkid.cb := Last_CB;
          if Succeeded( Parent.GetAttributesOf(1, LastPIDL, Flags)) then
            Result := Flags and SFGAO_FOLDER <> 0
        end
      finally
        if LastPIDL^.mkid.cb = 0 then
          LastPIDL^.mkid.cb := Last_CB;
      end

Why? `PIDLMgr.StripLastID` may return `nil` for `LastPIDL`, which will lead to an access violation. This has happend before for a similar code base (see discussion for https://github.com/pyscripter/MustangpeakCommonLib/issues/6). 

Maybe the fix for https://github.com/pyscripter/MustangpeakCommonLib/issues/6 already fixes this, but I did not dive deep enough into the code to understand how this could work.

**Comment by yonojoy** [comment]
see also https://github.com/TurboPack/MustangpeakCommonLib/commit/f8d198c4cbc1aa65687e23ff94d721f6968dcae3

**Comment by pyscripter** [comment]
I have added your fix and the same  fix in one more place.

**Comment by JamesS100** [comment]
I think I have found a problem in the change you made for MPCommonUtilities for this
In the function PIDLToPath you put
`       if Assigned(LastPIDL) then
`

But in this function the PItemIDList variable is called LastID not LastPIDL.

**Comment by pyscripter** [comment]
Thank you.  You are right.  Will be fixed shortly.
