### ISSUE TITLE
[dcc32 Error] MPCommonObjects.pas(2371): E2003 Undeclared identifier: 'InitAlpha'

### ISSUE THREAD

**Issue by ykang2000** [pyscripter/MustangpeakCommonLib#12]
My development environment is Delphi XE 10.4.2, and the [Tools-Options-Language-Delphi-library path] has been correctly set. When installing this control, a compile error occurs, and from the compilation error message, it appears that InitAlpha is a procedure but its definition cannot be found.

**Comment by pyscripter** [comment]
InitAlpha is a small function in Vcl.GraphUtils.  Is this not present in XE?

**Comment by ykang2000** [comment]
In Delphi XE 10.4.2, the Vcl.Graphics.pas unit does not contain a procedure named InitAlpha. I re-downloaded MustangpeakCommonLib from turbopack, and in the MPCommonObjects.pas file within it, there is no usage of the InitAlpha procedure; as a result, the compilation was successful.

**Comment by pyscripter** [comment]
If you got your job done with the Turbopack fork this fine.    I am targeting only more recent versions of Delphi.
