### ISSUE TITLE
MPCommonUtilities.pas - small bug

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/MustangpeakCommonLib#2]
```
You should not write
 SrvAPIHandle := CommonLoadLibrary('SVRAPI.DLL');
unconditionally.

A better code
 if Win32Platform = VER_PLATFORM_WIN32_WINDOWS then
    SrvAPIHandle := CommonLoadLibrary('SVRAPI.DLL');

Reason:
Some old apps copy SVRAPI.DLL into System32.
DllEntry of this library seems to load old kernel function 
converttoglobalhandle and displays error message.



```

Original issue reported on code.google.com by `m...@karsyan.com` on 31 Mar 2012 at 11:34

**Comment by pyscripter** [comment]
Agree but the code is like this:

    if Win32Platform = VER_PLATFORM_WIN32_NT then
    begin
      ....
    end else
    begin
      SrvAPIHandle := CommonLoadLibrary('SVRAPI.DLL');  // Windows 95/98 only

So it would only try to load if Win32Platform is either VER_PLATFORM_WIN32_WINDOWS or VER_PLATFORM_WIN32s (Windows 3.1!).
